import {
  colorVars,
  radiusVars,
  shadowVars,
  sizeVars,
  spacingVars,
  typeScaleVars,
  typographyVars,
} from '@foldstryx/tokens/index.stylex.ts'
import * as stylex from '@stylexjs/stylex'

export const calendarStyles = stylex.create({
  root: {
    boxSizing: 'border-box',
    minWidth: '220px',
    padding: spacingVars['--spacing-3'],
    backgroundColor: colorVars['--color-background-popover'],
    borderRadius: radiusVars['--radius-container'],
    boxShadow: shadowVars['--shadow-med'],
    color: colorVars['--color-text-primary'],
    fontFamily: typographyVars['--font-family-body'],
  },
  header: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: spacingVars['--spacing-2'],
    marginBottom: spacingVars['--spacing-2'],
  },
  navButton: {
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    width: sizeVars['--size-element-md'],
    height: sizeVars['--size-element-md'],
    padding: 0,
    borderWidth: 0,
    borderStyle: 'none',
    borderRadius: radiusVars['--radius-element'],
    backgroundColor: 'transparent',
    color: colorVars['--color-icon-secondary'],
    cursor: 'pointer',
    outline: 'none',
  },
  headingButton: {
    flexGrow: 1,
    padding: 0,
    borderWidth: 0,
    borderStyle: 'none',
    backgroundColor: 'transparent',
    fontSize: typeScaleVars['--text-label-size'],
    fontWeight: typeScaleVars['--text-label-weight'],
    color: colorVars['--color-text-primary'],
    cursor: 'pointer',
    textAlign: 'center',
    outline: 'none',
  },
  grid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(7, 1fr)',
    gap: 0,
  },
  weekRow: {
    display: 'contents',
  },
  headerRow: {
    display: 'contents',
  },
  pickerGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(4, 1fr)',
    gap: 0,
  },
  dayName: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    height: sizeVars['--size-element-md'],
    fontSize: typeScaleVars['--text-supporting-size'],
    color: colorVars['--color-text-secondary'],
  },
  dayCell: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    height: sizeVars['--size-element-md'],
    isolation: 'isolate',
  },
  dayButton: {
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    width: sizeVars['--size-element-sm'],
    height: sizeVars['--size-element-sm'],
    padding: 0,
    borderWidth: 0,
    borderStyle: 'none',
    borderRadius: radiusVars['--radius-full'],
    backgroundColor: 'transparent',
    fontSize: typeScaleVars['--text-body-size'],
    color: colorVars['--color-text-primary'],
    cursor: 'pointer',
    outline: 'none',
  },
  dayOutside: {
    opacity: 0.5,
    color: colorVars['--color-text-secondary'],
  },
  dayToday: {
    boxShadow: `inset 0 0 0 1px ${colorVars['--color-border-emphasized']}`,
  },
  daySelected: {
    backgroundColor: colorVars['--color-accent'],
    color: colorVars['--color-on-accent'],
  },
  dayDisabled: {
    opacity: 0.3,
    cursor: 'not-allowed',
  },
})
