import {
  colorVars,
  fontWeightVars,
  radiusVars,
  shadowVars,
  spacingVars,
  typeScaleVars,
  typographyVars,
} from '@foldstryx/tokens/index.stylex.ts'
import * as stylex from '@stylexjs/stylex'

export const dialogStyles = stylex.create({
  dialog: {
    backgroundColor: 'transparent',
    borderStyle: 'none',
    color: colorVars['--color-text-primary'],
    fontFamily: typographyVars['--font-family-body'],
    margin: 0,
    padding: 0,
  },
  dialogOpen: {
    alignItems: 'center',
    display: 'flex',
    justifyContent: 'center',
    maxHeight: '100vh',
    maxWidth: '100vw',
    width: '100%',
  },
  backdrop: {
    backdropFilter: 'blur(2px)',
    backgroundColor: colorVars['--color-overlay'],
    inset: 0,
    position: 'fixed',
    zIndex: 50,
  },
  panel: {
    backgroundColor: colorVars['--color-background-popover'],
    borderRadius: radiusVars['--radius-container'],
    boxShadow: shadowVars['--shadow-high'],
    color: colorVars['--color-text-primary'],
    display: 'grid',
    fontSize: typeScaleVars['--text-body-size'],
    gap: spacingVars['--spacing-4'],
    lineHeight: typeScaleVars['--text-body-leading'],
    maxWidth: 'calc(100% - 2rem)',
    padding: spacingVars['--spacing-4'],
    position: 'relative',
    width: '100%',
    zIndex: 50,
  },
  panelSm: {
    maxWidth: '24rem',
  },
  header: {
    display: 'flex',
    flexDirection: 'column',
    gap: spacingVars['--spacing-2'],
  },
  footer: {
    display: 'flex',
    flexDirection: {
      default: 'column-reverse',
      '@media (min-width: 640px)': 'row',
    },
    gap: spacingVars['--spacing-2'],
    justifyContent: {
      default: 'flex-start',
      '@media (min-width: 640px)': 'flex-end',
    },
  },
  title: {
    color: colorVars['--color-text-primary'],
    fontFamily: typographyVars['--font-family-heading'],
    fontSize: typeScaleVars['--text-heading-3-size'],
    fontWeight: fontWeightVars['--font-weight-semibold'],
    lineHeight: typeScaleVars['--text-heading-3-leading'],
    margin: 0,
  },
  description: {
    color: colorVars['--color-text-secondary'],
    fontSize: typeScaleVars['--text-body-size'],
    lineHeight: typeScaleVars['--text-body-leading'],
    margin: 0,
  },
  close: {
    alignItems: 'center',
    backgroundColor: {
      default: 'transparent',
      ':hover': colorVars['--color-overlay-hover'],
    },
    borderStyle: 'none',
    borderRadius: radiusVars['--radius-inner'],
    color: {
      default: colorVars['--color-text-secondary'],
      ':hover': colorVars['--color-text-primary'],
    },
    cursor: 'pointer',
    display: 'flex',
    fontSize: typeScaleVars['--text-large-size'],
    height: '2rem',
    justifyContent: 'center',
    lineHeight: typeScaleVars['--text-body-leading'],
    padding: 0,
    position: 'absolute',
    right: spacingVars['--spacing-2'],
    top: spacingVars['--spacing-2'],
    width: '2rem',
    zIndex: 1,
  },
  body: {
    display: 'flex',
    flexDirection: 'column',
    gap: spacingVars['--spacing-2'],
  },
})
