import {
  borderVars,
  colorVars,
  durationVars,
  easeVars,
  fontWeightVars,
  radiusVars,
  shadowVars,
  sizeVars,
  spacingVars,
  typeScaleVars,
  typographyVars,
} from '@foldstryx/tokens/index.stylex.ts'
import * as stylex from '@stylexjs/stylex'

export const sidebarStyles = stylex.create({
  shell: {
    backgroundColor: colorVars['--color-background-body'],
    display: 'flex',
    minHeight: '100vh',
    width: '100%',
  },
  desktop: {
    backgroundColor: 'inherit',
    boxSizing: 'border-box',
    display: 'flex',
    flexDirection: 'column',
    flexShrink: 0,
    minHeight: '100vh',
    overflow: 'hidden',
    width: '260px',
  },
  desktopCollapsed: {
    alignItems: 'center',
    overflow: 'visible',
    width: spacingVars['--spacing-12'],
  },
  brand: {
    alignItems: 'center',
    display: 'flex',
    flexShrink: 0,
    gap: spacingVars['--spacing-2'],
    minHeight: spacingVars['--spacing-8'],
    paddingBlock: spacingVars['--spacing-2'],
    paddingInline: spacingVars['--spacing-2'],
  },
  brandCollapsed: {
    justifyContent: 'center',
    paddingInline: 0,
  },
  brandText: {
    display: 'flex',
    flex: '1',
    flexDirection: 'column',
    minWidth: 0,
  },
  brandName: {
    color: colorVars['--color-text-primary'],
    fontFamily: typographyVars['--font-family-heading'],
    fontSize: typeScaleVars['--text-large-size'],
    fontWeight: fontWeightVars['--font-weight-semibold'],
    lineHeight: typeScaleVars['--text-large-leading'],
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  brandSubtitle: {
    color: colorVars['--color-text-secondary'],
    fontSize: typeScaleVars['--text-supporting-size'],
    lineHeight: typeScaleVars['--text-supporting-leading'],
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  nav: {
    display: 'flex',
    flex: '1',
    flexDirection: 'column',
    minHeight: 0,
    overflowX: 'hidden',
    overflowY: 'auto',
    paddingBlockEnd: spacingVars['--spacing-2'],
    paddingBlockStart: spacingVars['--spacing-1'],
    paddingInline: spacingVars['--spacing-2'],
  },
  navCollapsed: {
    alignItems: 'center',
    overflow: 'visible',
  },
  group: {
    display: 'flex',
    flexDirection: 'column',
    paddingBlock: spacingVars['--spacing-1'],
  },
  groupItems: {
    display: 'flex',
    flexDirection: 'column',
    gap: spacingVars['--spacing-0-5'],
  },
  groupLabel: {
    color: colorVars['--color-text-secondary'],
    fontSize: typeScaleVars['--text-supporting-size'],
    fontWeight: fontWeightVars['--font-weight-semibold'],
    lineHeight: typeScaleVars['--text-supporting-leading'],
    paddingBlock: spacingVars['--spacing-1'],
    paddingInline: spacingVars['--spacing-2'],
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  visuallyHidden: {
    borderWidth: 0,
    clip: 'rect(0, 0, 0, 0)',
    height: '1px',
    margin: '-1px',
    overflow: 'hidden',
    padding: 0,
    position: 'absolute',
    whiteSpace: 'nowrap',
    width: '1px',
  },
  item: {
    alignItems: 'center',
    borderRadius: radiusVars['--radius-element'],
    borderStyle: 'none',
    borderWidth: 0,
    boxSizing: 'border-box',
    color: colorVars['--color-text-primary'],
    cursor: 'pointer',
    display: 'flex',
    flexShrink: 0,
    fontFamily: 'inherit',
    fontSize: typeScaleVars['--text-label-size'],
    fontWeight: fontWeightVars['--font-weight-normal'],
    gap: spacingVars['--spacing-2'],
    height: sizeVars['--size-element-md'],
    lineHeight: typeScaleVars['--text-label-leading'],
    minWidth: 0,
    outline: 'none',
    paddingBlock: 0,
    paddingInline: spacingVars['--spacing-2'],
    textAlign: 'start',
    width: '100%',
    backgroundColor: {
      default: 'transparent',
      ':hover': colorVars['--color-overlay-hover'],
      ':active': colorVars['--color-overlay-pressed'],
    },
    boxShadow: {
      default: 'none',
      ':focus-visible': shadowVars['--shadow-inset-selected'],
    },
  },
  itemActive: {
    fontWeight: fontWeightVars['--font-weight-medium'],
    backgroundColor: {
      default: colorVars['--color-neutral'],
      ':hover': colorVars['--color-neutral'],
      ':active': colorVars['--color-neutral'],
    },
  },
  itemCollapsed: {
    justifyContent: 'center',
    paddingInline: 0,
    width: sizeVars['--size-element-md'],
  },
  itemContent: {
    alignItems: 'center',
    display: 'flex',
    flex: '1',
    gap: spacingVars['--spacing-2'],
    minWidth: 0,
    overflow: 'hidden',
  },
  itemLabel: {
    flex: '1',
    minWidth: 0,
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  splitAction: {
    alignItems: 'center',
    backgroundColor: 'transparent',
    borderStyle: 'none',
    borderWidth: 0,
    color: 'inherit',
    cursor: 'pointer',
    display: 'flex',
    flex: '1',
    fontFamily: 'inherit',
    fontSize: 'inherit',
    fontWeight: 'inherit',
    gap: spacingVars['--spacing-2'],
    lineHeight: 'inherit',
    minWidth: 0,
    outline: 'none',
    padding: 0,
    textAlign: 'start',
  },
  itemRow: {
    alignItems: 'center',
    borderRadius: radiusVars['--radius-element'],
    display: 'flex',
    minWidth: 0,
    width: '100%',
  },
  itemTrailing: {
    color: colorVars['--color-text-secondary'],
    flexShrink: 0,
    fontSize: typeScaleVars['--text-supporting-size'],
  },
  itemExpandIcon: {
    alignItems: 'center',
    display: 'inline-flex',
    flexShrink: 0,
    height: spacingVars['--spacing-6'],
    justifyContent: 'center',
    transform: 'rotate(180deg)',
    transitionDuration: durationVars['--duration-fast'],
    transitionProperty: 'transform',
    transitionTimingFunction: easeVars['--ease-standard'],
    width: spacingVars['--spacing-6'],
  },
  itemExpandIconClosed: { transform: 'none' },
  collapseButton: {
    alignItems: 'center',
    backgroundColor: {
      default: 'transparent',
      ':hover': colorVars['--color-overlay-hover'],
    },
    borderRadius: radiusVars['--radius-element'],
    borderStyle: 'none',
    borderWidth: 0,
    color: colorVars['--color-icon-secondary'],
    cursor: 'pointer',
    display: 'inline-flex',
    height: sizeVars['--size-element-md'],
    justifyContent: 'center',
    width: sizeVars['--size-element-md'],
  },
  collapseIcon: {
    alignItems: 'center',
    display: 'inline-flex',
    transitionDuration: durationVars['--duration-fast'],
    transitionProperty: 'transform',
    transitionTimingFunction: easeVars['--ease-standard'],
  },
  collapseIconCollapsed: { transform: 'rotate(180deg)' },
  flyout: {
    backgroundColor: colorVars['--color-background-popover'],
    borderColor: colorVars['--color-border'],
    borderRadius: radiusVars['--radius-element'],
    borderStyle: 'solid',
    borderWidth: borderVars['--border-width'],
    boxShadow: shadowVars['--shadow-high'],
    left: '100%',
    marginInlineStart: spacingVars['--spacing-1'],
    minWidth: '180px',
    paddingBlock: spacingVars['--spacing-1'],
    paddingInline: spacingVars['--spacing-1'],
    position: 'absolute',
    top: 0,
    zIndex: 20,
  },
  flyoutHeader: {
    color: colorVars['--color-text-secondary'],
    fontSize: typeScaleVars['--text-supporting-size'],
    fontWeight: fontWeightVars['--font-weight-semibold'],
    lineHeight: typeScaleVars['--text-supporting-leading'],
    paddingBlock: spacingVars['--spacing-1'],
    paddingInline: spacingVars['--spacing-2'],
  },
  tooltip: {
    backgroundColor: colorVars['--color-background-popover'],
    borderColor: colorVars['--color-border'],
    borderRadius: radiusVars['--radius-element'],
    borderStyle: 'solid',
    borderWidth: borderVars['--border-width'],
    color: colorVars['--color-text-primary'],
    fontSize: typeScaleVars['--text-supporting-size'],
    left: '100%',
    lineHeight: typeScaleVars['--text-supporting-leading'],
    marginInlineStart: spacingVars['--spacing-1'],
    paddingBlock: spacingVars['--spacing-1'],
    paddingInline: spacingVars['--spacing-2'],
    position: 'absolute',
    top: '50%',
    transform: 'translateY(-50%)',
    whiteSpace: 'nowrap',
    zIndex: 20,
  },
  itemRoot: {
    position: 'relative',
    width: '100%',
  },
  itemRootCollapsed: {
    display: 'flex',
    justifyContent: 'center',
    width: 'auto',
  },
  expandButton: {
    alignItems: 'center',
    borderRadius: radiusVars['--radius-element'],
    borderStyle: 'none',
    borderWidth: 0,
    color: 'inherit',
    cursor: 'pointer',
    display: 'inline-flex',
    flexShrink: 0,
    height: spacingVars['--spacing-6'],
    justifyContent: 'center',
    margin: 0,
    outline: 'none',
    padding: 0,
    width: spacingVars['--spacing-6'],
    backgroundColor: {
      default: 'transparent',
      ':hover': colorVars['--color-overlay-hover'],
      ':active': colorVars['--color-overlay-pressed'],
    },
    boxShadow: {
      default: 'none',
      ':focus-visible': shadowVars['--shadow-inset-selected'],
    },
  },
  icon: {
    color: colorVars['--color-icon-secondary'],
    display: 'flex',
    flexShrink: 0,
  },
  iconSelected: { color: colorVars['--color-icon-primary'] },
  children: {
    display: 'grid',
    gridTemplateRows: '1fr',
    transitionDuration: durationVars['--duration-medium'],
    transitionProperty: 'grid-template-rows',
    transitionTimingFunction: easeVars['--ease-standard'],
  },
  childrenCollapsed: { gridTemplateRows: '0fr' },
  childrenInner: {
    display: 'flex',
    flexDirection: 'column',
    gap: spacingVars['--spacing-0-5'],
    minHeight: 0,
    overflow: 'hidden',
    paddingInlineStart: spacingVars['--spacing-6'],
  },
  footer: {
    borderBlockStartColor: colorVars['--color-border'],
    borderBlockStartStyle: 'solid',
    borderBlockStartWidth: borderVars['--border-width'],
    display: 'flex',
    flexDirection: 'column',
    flexShrink: 0,
    gap: spacingVars['--spacing-0-5'],
    marginTop: 'auto',
    paddingBlockEnd: spacingVars['--spacing-2'],
    paddingBlockStart: spacingVars['--spacing-1'],
    paddingInline: spacingVars['--spacing-2'],
  },
  footerCollapsed: {
    alignItems: 'center',
    borderBlockStartStyle: 'none',
    paddingBlockStart: 0,
  },
  footerIcons: {
    alignItems: 'center',
    display: 'flex',
    gap: spacingVars['--spacing-1'],
  },
  footerIconsCollapsed: {
    alignItems: 'center',
    flexDirection: 'column',
  },
  footerIconButton: {
    alignItems: 'center',
    backgroundColor: {
      default: 'transparent',
      ':hover': colorVars['--color-overlay-hover'],
    },
    borderRadius: radiusVars['--radius-element'],
    borderStyle: 'none',
    borderWidth: 0,
    color: colorVars['--color-icon-secondary'],
    cursor: 'pointer',
    display: 'inline-flex',
    height: sizeVars['--size-element-md'],
    justifyContent: 'center',
    width: sizeVars['--size-element-md'],
  },
  user: {
    color: colorVars['--color-text-secondary'],
    display: 'flex',
    flexDirection: 'column',
    fontSize: typeScaleVars['--text-supporting-size'],
    gap: spacingVars['--spacing-0-5'],
    lineHeight: typeScaleVars['--text-supporting-leading'],
    minWidth: 0,
    overflow: 'hidden',
    paddingBlock: spacingVars['--spacing-1'],
    paddingInline: spacingVars['--spacing-2'],
  },
  inset: {
    backgroundColor: colorVars['--color-background-body'],
    display: 'flex',
    flex: '1',
    flexDirection: 'column',
    minHeight: '100vh',
    minWidth: 0,
    overflow: 'hidden',
  },
  insetHeader: {
    alignItems: 'center',
    backgroundColor: colorVars['--color-background-body'],
    borderBlockEndColor: colorVars['--color-border'],
    borderBlockEndStyle: 'solid',
    borderBlockEndWidth: borderVars['--border-width'],
    display: 'flex',
    flexShrink: 0,
    gap: spacingVars['--spacing-3'],
    minHeight: spacingVars['--spacing-12'],
    paddingBlock: spacingVars['--spacing-2'],
    paddingInline: spacingVars['--spacing-4'],
  },
  insetMain: { flex: '1', minWidth: 0 },
  collapse: {
    alignItems: 'center',
    backgroundColor: {
      default: 'transparent',
      ':hover': colorVars['--color-overlay-hover'],
    },
    borderRadius: radiusVars['--radius-element'],
    borderStyle: 'none',
    borderWidth: 0,
    color: {
      default: colorVars['--color-text-secondary'],
      ':hover': colorVars['--color-text-primary'],
    },
    cursor: 'pointer',
    display: 'flex',
    padding: spacingVars['--spacing-2'],
  },
})
