import {
  borderVars,
  colorVars,
  fontWeightVars,
  radiusVars,
  shadowVars,
  spacingVars,
  typeScaleVars,
  typographyVars,
} from '@foldstryx/tokens/index.stylex.ts'
import * as stylex from '@stylexjs/stylex'

export const toastStyles = stylex.create({
  entry: {
    backgroundColor: colorVars['--color-background-popover'],
    borderColor: colorVars['--color-border'],
    borderRadius: radiusVars['--radius-element'],
    borderStyle: 'solid',
    borderWidth: borderVars['--border-width'],
    boxShadow: shadowVars['--shadow-med'],
    color: colorVars['--color-text-primary'],
    display: 'flex',
    flexDirection: 'column',
    fontSize: typeScaleVars['--text-body-size'],
    gap: spacingVars['--spacing-1'],
    lineHeight: typeScaleVars['--text-body-leading'],
    overflow: 'hidden',
    padding: spacingVars['--spacing-3'],
    paddingRight: spacingVars['--spacing-9'],
    pointerEvents: 'auto',
    position: 'relative',
    width: '100%',
  },
  entrySuccess: {
    backgroundColor: colorVars['--color-success-muted'],
    borderColor: colorVars['--color-success'],
    color: colorVars['--color-success'],
  },
  entryWarning: {
    backgroundColor: colorVars['--color-warning-muted'],
    borderColor: colorVars['--color-warning'],
    color: colorVars['--color-warning'],
  },
  entryError: {
    backgroundColor: colorVars['--color-error-muted'],
    borderColor: colorVars['--color-error'],
    color: colorVars['--color-error'],
  },
  title: {
    fontFamily: typographyVars['--font-family-heading'],
    fontWeight: fontWeightVars['--font-weight-medium'],
    lineHeight: typeScaleVars['--text-body-leading'],
    margin: 0,
  },
  description: {
    fontWeight: fontWeightVars['--font-weight-normal'],
    lineHeight: typeScaleVars['--text-body-leading'],
    margin: 0,
    opacity: 0.9,
  },
  dismiss: {
    alignItems: 'center',
    backgroundColor: 'transparent',
    borderStyle: 'none',
    borderRadius: radiusVars['--radius-inner'],
    color: {
      default: colorVars['--color-text-secondary'],
      ':hover': colorVars['--color-text-primary'],
    },
    cursor: 'pointer',
    display: 'flex',
    height: '1.5rem',
    justifyContent: 'center',
    padding: spacingVars['--spacing-1'],
    position: 'absolute',
    right: spacingVars['--spacing-1-5'],
    top: spacingVars['--spacing-1-5'],
    width: '1.5rem',
  },
})
